### ISSUE TITLE
huge amount of packages deprecated

### ISSUE THREAD

**Issue by rickersilva** [Payerset/parquet-editor#1]
I'm tryin to use this, but it turns out that all packages are deprecated and throw alot of errors and warnings when installing dependencies.

Are there any plans to update this project. I find it quite unusual since the project is practically new, a couple of weeks.

**Comment by jerrypayerset** [comment]
> I'm tryin to use this, but it turns out that all packages are deprecated and throw alot of errors and warnings when installing dependencies.
> 
> Are there any plans to update this project. I find it quite unusual since the project is practically new, a couple of weeks.

Ahoy there sir - yes there are a number of issues with the DuckDB nodejs client, including the deprecated dependencies. There is a new client that is available, and we'll be updating this to use the new client shortly.

**Comment by jerrypayerset** [comment]
This has been updated to use the latest DuckDB node API @rickersilva - the memory leak issues are resolved.
